# Generated by Django 4.2.20 on 2025-03-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="menu", old_name="price", new_name="Price",),
        migrations.AlterField(
            model_name="booking", name="No_of_guests", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="menu", name="Inventory", field=models.IntegerField(),
        ),
    ]
